language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_github wch/R6
  - ./travis-tool.sh r_binary_install testthat
  - ./travis-tool.sh r_binary_install igraph
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package jimhester/covr

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'library(covr);coveralls()'
