---
title: "Development notes for bitphyloR"
author: "Ke Yuan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


# Testing TSSB class

Initiating a `Node` object 
```{r}
library(bitphyloR)
n0 <- Node$new()
```

```{r}
set.seed(9)
tssb <- TSSB$new(n0, data = matrix(rnorm(50),50,1), dpAlpha = 1, dpGamma = 1,
                 dpLambda = 1)
```

```{r}
res <- tssb$GetMixture()
barplot(res$weight)
```


```{r}
res2 <- tssb$ConvertTssbToIgraph()
g <- res2$g
plot.igraph(g, layout = layout.reingold.tilford(g), 
     vertex.label = get.vertex.attribute(g, name = "size"),
     edge.arrow.size = 0.1)
```

```{r}
tssb$CullTree()
res3 <- tssb$ConvertTssbToIgraph()
g <- res3$g
plot.igraph(g, layout = layout.reingold.tilford(g), 
     vertex.label = get.vertex.attribute(g, name = "size"),
     edge.arrow.size = 0.1)

```


# Inference objects 
```{r}
n0 <- Node$new()
set.seed(9)
tssbMCMC <- TssbMCMC$new(n0, data = matrix(rnorm(50),50,1), dpAlpha = 1, dpGamma = 1,
                 dpLambda = 1)
```

```{r}
res <- tssbMCMC$GetMixture()
barplot(res$weight)
```
