---
title: "Tree-structured stick breaking process"
author: "Ke Yuan"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: null
    css: wch_style.css
    toc: true
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r echo = FALSE}
# wch's setting 
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

## The TSSB prior 

To illustrate the TSSB prior, we load the `bitphyloR` package and initiate a `Node` object. 
```{r}
library(bitphyloR)
n0 <- Node$new()
```
The `Node` object is the basic class representing components in the mixture. 
```{r}
n0
```

Now, let's initiate a `TSSB` object. In this case, 
```{r}
fixedSeed <- 9
set.seed(fixedSeed)
tssb <- TSSB$new(n0, data = matrix(rnorm(50),50,1), dpAlpha = 1, dpGamma = 1,
                 dpLambda = 1)
tssb
```

```{r}
res <- tssb$GetMixture()
barplot(res$weight)
```


```{r}
res2 <- tssb$ConvertTssbToIgraph()
g <- res2$g
plot.igraph(g, layout = layout.reingold.tilford(g), 
     vertex.label = get.vertex.attribute(g, name = "size"),
     vertex.size = 15, edge.arrow.size = 0.5)
```


```{r}
tssb$CullTree()
res3 <- tssb$ConvertTssbToIgraph()
g <- res3$g
plot.igraph(g, layout = layout.reingold.tilford(g), 
     vertex.label = get.vertex.attribute(g, name = "size"),
     vertex.size = 15, edge.arrow.size = 0.5)
```

## Inference classes 
```{r}
set.seed(fixedSeed)
tssbMCMC <- TssbMCMC$new(n0, data = matrix(rnorm(50),50,1), dpAlpha = 1, dpGamma = 1, dpLambda = 1)
```

```{r}
res <- tssbMCMC$GetMixture()
barplot(res$weight)
sum(res$weight)
```

```{r}
tssbMCMC$ResampleSticks()
res <- tssbMCMC$GetMixture()
barplot(res$weight)
sum(res$weight)
```

```{r}
tssbMCMC$CullTree()
g <- tssbMCMC$ConvertTssbToIgraph()$g
plot.igraph(g, layout = layout.reingold.tilford(g), 
     vertex.label = get.vertex.attribute(g, name = "size"),
     vertex.size = 15, edge.arrow.size = 0.5)
```

```{r}
g <- tssbMCMC$ResampleStickOrders()$ConvertTssbToIgraph()$g
plot.igraph(g, layout = layout.reingold.tilford(g), 
     vertex.label = get.vertex.attribute(g, name = "size"),
     vertex.size = 15, edge.arrow.size = 0.5)
```

```{r}
g <- tssbMCMC$ResampleStickOrders()$ConvertTssbToIgraph()$g
plot.igraph(g, layout = layout.reingold.tilford(g), 
     vertex.label = get.vertex.attribute(g, name = "size"),
     vertex.size = 15, edge.arrow.size = 0.5)
```

